[project]
name = "odoo-addons-oca-multi-company"
version = "17.0.20240516.0"
dependencies = [
    "odoo-addon-mail_multicompany>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
