[project]
name = "odoo-addons-oca-report-print-send"
version = "17.0.20240308.0"
dependencies = [
    "odoo-addon-base_report_to_printer>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
