[project]
name = "odoo-addons-oca-account-invoice-reporting"
version = "17.0.20240314.0"
dependencies = [
    "odoo-addon-account_invoice_line_report>=17.0dev,<17.1dev",
    "odoo-addon-account_invoice_report_grouped_by_picking>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
