[project]
name = "odoo-addons-oca-rma"
version = "18.0.20251105.0"
dependencies = [
    "odoo-addon-product_warranty==18.0.*",
    "odoo-addon-rma==18.0.*",
    "odoo-addon-rma_lot==18.0.*",
    "odoo-addon-rma_reason==18.0.*",
    "odoo-addon-rma_sale==18.0.*",
    "odoo-addon-rma_sale_reason==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
