[project]
name = "odoo-addons-oca-hr-expense"
version = "17.0.20240524.0"
dependencies = [
    "odoo-addon-hr_expense_payment>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
