[project]
name = "odoo-addons-oca-sale-reporting"
version = "17.0.20240521.0"
dependencies = [
    "odoo-addon-sale_order_line_position>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
