[project]
name = "odoo-addons-oca-account-payment"
version = "17.0.20240314.0"
dependencies = [
    "odoo-addon-account_due_list>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
