import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo-addons-oca-multi-company",
    description="Meta package for oca-multi-company Odoo addons",
    version=version,
    install_requires=[
        'odoo-addon-account_invoice_inter_company>=16.0dev,<16.1dev',
        'odoo-addon-account_move_change_company>=16.0dev,<16.1dev',
        'odoo-addon-account_multicompany_easy_creation>=16.0dev,<16.1dev',
        'odoo-addon-account_reconcile_model_multicompany_propagate>=16.0dev,<16.1dev',
        'odoo-addon-base_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-calendar_event_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-calendar_event_type_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-company_dependent_flag>=16.0dev,<16.1dev',
        'odoo-addon-crm_lost_reason_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-crm_stage_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-crm_tag_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-crm_tag_multi_company_event_crm>=16.0dev,<16.1dev',
        'odoo-addon-crm_tag_multi_company_sale>=16.0dev,<16.1dev',
        'odoo-addon-ir_actions_report_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-ir_config_parameter_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-login_all_company>=16.0dev,<16.1dev',
        'odoo-addon-mail_multicompany>=16.0dev,<16.1dev',
        'odoo-addon-mail_template_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-mass_mailing_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-partner_account_multicompany_default>=16.0dev,<16.1dev',
        'odoo-addon-partner_category_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-partner_category_multi_company_account>=16.0dev,<16.1dev',
        'odoo-addon-partner_category_multi_company_analytic>=16.0dev,<16.1dev',
        'odoo-addon-partner_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-pos_category_multicompany>=16.0dev,<16.1dev',
        'odoo-addon-pos_restaurant_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-product_account_multicompany_default>=16.0dev,<16.1dev',
        'odoo-addon-product_category_company>=16.0dev,<16.1dev',
        'odoo-addon-product_category_company_favorite>=16.0dev,<16.1dev',
        'odoo-addon-product_default_code_res_company_code>=16.0dev,<16.1dev',
        'odoo-addon-product_multi_company>=16.0dev,<16.1dev',
        'odoo-addon-product_tax_multicompany_default>=16.0dev,<16.1dev',
        'odoo-addon-purchase_sale_container_deposit_inter_company>=16.0dev,<16.1dev',
        'odoo-addon-purchase_sale_inter_company>=16.0dev,<16.1dev',
        'odoo-addon-purchase_sale_stock_inter_company>=16.0dev,<16.1dev',
        'odoo-addon-purchase_sale_stock_inter_company_mrp>=16.0dev,<16.1dev',
        'odoo-addon-res_company_active>=16.0dev,<16.1dev',
        'odoo-addon-res_company_category>=16.0dev,<16.1dev',
        'odoo-addon-res_company_code>=16.0dev,<16.1dev',
        'odoo-addon-res_company_search_view>=16.0dev,<16.1dev',
        'odoo-addon-sale_partner_company>=16.0dev,<16.1dev',
        'odoo-addon-sale_product_company>=16.0dev,<16.1dev',
        'odoo-addon-sale_product_company_multi_add>=16.0dev,<16.1dev',
        'odoo-addon-sale_stock_warehouse_multicompany>=16.0dev,<16.1dev',
        'odoo-addon-stock_intercompany>=16.0dev,<16.1dev',
        'odoo-addon-stock_intercompany_bidirectional>=16.0dev,<16.1dev',
    ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
        'Framework :: Odoo :: 16.0',
    ]
)
